language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
  - /^(feature|bugfix)\/.*$/
before_install:
 - chmod +x gradlew
script: ./gradlew check
jobs:
  include:
    - stage: test
      script: ./gradlew test jacocoTestReport
  